Resolves Issue #32
safe-together/specification pull request #34
Opened 2020-04-28 14:35 UTC by YassineOuahidi

2020-04-28 16:50 UTC, ecow requested changes
Preferirei  lasciare come titolo Marco the volunteer.

Il fatto che a Marco interessi fare il volontario guida buona parte dei suoi comportamenti

Non è una cosa imporytante ma volevo provare come funziona "request chamgers"

2020-04-28 16:52 UTC, ecow requested changes
Mi sembra manchi la modifica ai needs dove si citano Anne e Jack

2020-04-28 19:37 UTC, LeonardoLonghi commented
Sul fatto di lasciare marco come volontario non sono molto convinto. Buona parte delle sue azioni sono mosse dal suo essere volontario perchè fino ad ora lo abbiamo visto come tale. Più che altro il problema è nei needs.  I needs che ha ora marco li ha come volontario. Togliendo Anne e Jack alcuni dei loro needs verrebbero presi da marco, ma non sono più needs come volontario ma come cittadino.

2020-04-29 16:38 UTC, ecow commented
Certo, marco in quanto volontario è anche un cittadino con tutti i needs di Anne e di Jack. Il concetto di volontario è molto ampio. Ad esempio i partecipanti a g0v.it sono tutti volontari, anche se non è detto . Marco il cittadino mi ricrda troppo la rivoluzione Francese :-)  Potremmo anche chimarlo marco il biondo (se diciamo che ha i capelli biondi. O marco il piedone se diciamo che porta il 48 di scarpe. Il fatto che sia volontario anche nell'emergenza Covidi copre solo una piccola parte delle sue storie ma lo caratterizza umanamente. Potremmo non mettere nulla. Non è una cosa importante ma marketing. Mi piacerevve che Marco avesse una connotazione positiva nell'immaginario di chi legge. Potremmo anche chiamarlo  Marco il bravo ragazzo ma confligge platealmente con la storia in cui tenta di derubare Franca :-)

2020-04-30 19:26 UTC, merged